import type { Metadata } from "next";
import "./globals.css";

import { Roboto_Condensed } from "next/font/google";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const roboto_condensed_init = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["200", "300", "700"],
  variable: "--font-roboto_condensed",
});

export const metadata: Metadata = {
  title: "Maksimilijan Wine Room",
  description: "Generated by InnovaTech Development",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed_init.variable}>
        <NavBar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
